var mongoose = require('mongoose');
//mongoose.set('debug', true);
var userDB = mongoose.connect('mongodb://localhost/users');

var Schema = mongoose.Schema;
var passportLocalMongoose = require('passport-local-mongoose');

var NewAccount = new Schema({
  //'_id' used as userID for linking to other tables, autogenerated by DB
    username: String,
    password: String, 
    email: String,
    HID: String, 
    token: String
});
NewAccount.plugin(passportLocalMongoose, {usernameField: "email"});

//module.exports = userDB.model('Account', Account);
module.exports = {
    new_account: userDB.model('NewAccount', NewAccount),
};

